/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo.tables.records;


import com.rulerbug.zoo.tables.Allbooks;
import com.rulerbug.zoo.tables.interfaces.IAllbooks;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllbooksRecord extends UpdatableRecordImpl<AllbooksRecord> implements Record6<Long, String, String, String, LocalDateTime, LocalDateTime>, IAllbooks {

    private static final long serialVersionUID = -250942791;

    /**
     * Setter for <code>mypages.allBooks.id</code>. 书ID
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mypages.allBooks.id</code>. 书ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mypages.allBooks.bookName</code>. 书名
     */
    @Override
    public void setBookname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mypages.allBooks.bookName</code>. 书名
     */
    @Override
    public String getBookname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mypages.allBooks.author</code>. 作者
     */
    @Override
    public void setAuthor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mypages.allBooks.author</code>. 作者
     */
    @Override
    public String getAuthor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mypages.allBooks.password</code>. 写书的密码
     */
    @Override
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mypages.allBooks.password</code>. 写书的密码
     */
    @Override
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mypages.allBooks.createTime</code>. 开始创作时间
     */
    @Override
    public void setCreatetime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>mypages.allBooks.createTime</code>. 开始创作时间
     */
    @Override
    public LocalDateTime getCreatetime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>mypages.allBooks.changeTime</code>. 最后一次修改时间
     */
    @Override
    public void setChangetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>mypages.allBooks.changeTime</code>. 最后一次修改时间
     */
    @Override
    public LocalDateTime getChangetime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Allbooks.ALLBOOKS.ID;
    }

    @Override
    public Field<String> field2() {
        return Allbooks.ALLBOOKS.BOOKNAME;
    }

    @Override
    public Field<String> field3() {
        return Allbooks.ALLBOOKS.AUTHOR;
    }

    @Override
    public Field<String> field4() {
        return Allbooks.ALLBOOKS.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Allbooks.ALLBOOKS.CREATETIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Allbooks.ALLBOOKS.CHANGETIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBookname();
    }

    @Override
    public String component3() {
        return getAuthor();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatetime();
    }

    @Override
    public LocalDateTime component6() {
        return getChangetime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBookname();
    }

    @Override
    public String value3() {
        return getAuthor();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatetime();
    }

    @Override
    public LocalDateTime value6() {
        return getChangetime();
    }

    @Override
    public AllbooksRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AllbooksRecord value2(String value) {
        setBookname(value);
        return this;
    }

    @Override
    public AllbooksRecord value3(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public AllbooksRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AllbooksRecord value5(LocalDateTime value) {
        setCreatetime(value);
        return this;
    }

    @Override
    public AllbooksRecord value6(LocalDateTime value) {
        setChangetime(value);
        return this;
    }

    @Override
    public AllbooksRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAllbooks from) {
        setId(from.getId());
        setBookname(from.getBookname());
        setAuthor(from.getAuthor());
        setPassword(from.getPassword());
        setCreatetime(from.getCreatetime());
        setChangetime(from.getChangetime());
    }

    @Override
    public <E extends IAllbooks> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllbooksRecord
     */
    public AllbooksRecord() {
        super(Allbooks.ALLBOOKS);
    }

    /**
     * Create a detached, initialised AllbooksRecord
     */
    public AllbooksRecord(Long id, String bookname, String author, String password, LocalDateTime createtime, LocalDateTime changetime) {
        super(Allbooks.ALLBOOKS);

        set(0, id);
        set(1, bookname);
        set(2, author);
        set(3, password);
        set(4, createtime);
        set(5, changetime);
    }
}
