/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo.tables.records;


import com.rulerbug.zoo.tables.Pages;
import com.rulerbug.zoo.tables.interfaces.IPages;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagesRecord extends UpdatableRecordImpl<PagesRecord> implements Record8<Long, Long, Long, String, String, String, LocalDateTime, LocalDateTime>, IPages {

    private static final long serialVersionUID = -493408477;

    /**
     * Setter for <code>mypages.pages.id</code>. 文章ID
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mypages.pages.id</code>. 文章ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mypages.pages.bookId</code>. 书Id
     */
    @Override
    public void setBookid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mypages.pages.bookId</code>. 书Id
     */
    @Override
    public Long getBookid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mypages.pages.index</code>. 章节索引
     */
    @Override
    public void setIndex(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>mypages.pages.index</code>. 章节索引
     */
    @Override
    public Long getIndex() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>mypages.pages.title</code>. 文章标题
     */
    @Override
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mypages.pages.title</code>. 文章标题
     */
    @Override
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mypages.pages.smallTitle</code>. 文章小标题
     */
    @Override
    public void setSmalltitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mypages.pages.smallTitle</code>. 文章小标题
     */
    @Override
    public String getSmalltitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mypages.pages.context</code>. 文章内容
     */
    @Override
    public void setContext(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mypages.pages.context</code>. 文章内容
     */
    @Override
    public String getContext() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mypages.pages.firstCreatTime</code>. 创作时间
     */
    @Override
    public void setFirstcreattime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>mypages.pages.firstCreatTime</code>. 创作时间
     */
    @Override
    public LocalDateTime getFirstcreattime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>mypages.pages.changeTime</code>. 修改时间
     */
    @Override
    public void setChangetime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>mypages.pages.changeTime</code>. 修改时间
     */
    @Override
    public LocalDateTime getChangetime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Pages.PAGES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Pages.PAGES.BOOKID;
    }

    @Override
    public Field<Long> field3() {
        return Pages.PAGES.INDEX;
    }

    @Override
    public Field<String> field4() {
        return Pages.PAGES.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Pages.PAGES.SMALLTITLE;
    }

    @Override
    public Field<String> field6() {
        return Pages.PAGES.CONTEXT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Pages.PAGES.FIRSTCREATTIME;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Pages.PAGES.CHANGETIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getBookid();
    }

    @Override
    public Long component3() {
        return getIndex();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getSmalltitle();
    }

    @Override
    public String component6() {
        return getContext();
    }

    @Override
    public LocalDateTime component7() {
        return getFirstcreattime();
    }

    @Override
    public LocalDateTime component8() {
        return getChangetime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getBookid();
    }

    @Override
    public Long value3() {
        return getIndex();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getSmalltitle();
    }

    @Override
    public String value6() {
        return getContext();
    }

    @Override
    public LocalDateTime value7() {
        return getFirstcreattime();
    }

    @Override
    public LocalDateTime value8() {
        return getChangetime();
    }

    @Override
    public PagesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PagesRecord value2(Long value) {
        setBookid(value);
        return this;
    }

    @Override
    public PagesRecord value3(Long value) {
        setIndex(value);
        return this;
    }

    @Override
    public PagesRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public PagesRecord value5(String value) {
        setSmalltitle(value);
        return this;
    }

    @Override
    public PagesRecord value6(String value) {
        setContext(value);
        return this;
    }

    @Override
    public PagesRecord value7(LocalDateTime value) {
        setFirstcreattime(value);
        return this;
    }

    @Override
    public PagesRecord value8(LocalDateTime value) {
        setChangetime(value);
        return this;
    }

    @Override
    public PagesRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPages from) {
        setId(from.getId());
        setBookid(from.getBookid());
        setIndex(from.getIndex());
        setTitle(from.getTitle());
        setSmalltitle(from.getSmalltitle());
        setContext(from.getContext());
        setFirstcreattime(from.getFirstcreattime());
        setChangetime(from.getChangetime());
    }

    @Override
    public <E extends IPages> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagesRecord
     */
    public PagesRecord() {
        super(Pages.PAGES);
    }

    /**
     * Create a detached, initialised PagesRecord
     */
    public PagesRecord(Long id, Long bookid, Long index, String title, String smalltitle, String context, LocalDateTime firstcreattime, LocalDateTime changetime) {
        super(Pages.PAGES);

        set(0, id);
        set(1, bookid);
        set(2, index);
        set(3, title);
        set(4, smalltitle);
        set(5, context);
        set(6, firstcreattime);
        set(7, changetime);
    }
}
