## YAML Template.
---
server:
  port: 80
  tomcat:
    uri-encoding: utf-8
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    basedir: /home/cache/ #指定目录
  use-forward-headers: true
spring:

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  encoding:
    force: true
    charset: UTF-8
    enabled: true
  datasource:
    url: jdbc:mysql://106.13.176.31:3306/mypages?serverTime=Aisa/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2Y2w1s8vd5saAFgdQc8M
    # C3CCA85DC41E8AC91F140B3A547042EB
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
  freemarker:
    request-context-attribute: req  #req访问request
    allow-request-override: false
    suffix: .xhtml  #后缀名
    content-type: text/html
    cache: false #缓存配置
    template-loader-path: classpath:/assets
    check-template-location: true
    expose-session-attributes: false
    expose-request-attributes: false
    charset: UTF-8 #编码格式
    order: 1
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  application:
    name: 规则虫空间
  servlet:
    multipart:
      maxFileSize: 500MB
      maxRequestSize: 100MB
file:
  staticAccessPath: /file/**
  uploadFolder: /home/cache/

