/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo;


import com.rulerbug.zoo.tables.Allbooks;
import com.rulerbug.zoo.tables.Limit;
import com.rulerbug.zoo.tables.Pages;
import com.rulerbug.zoo.tables.Role;
import com.rulerbug.zoo.tables.User;
import com.rulerbug.zoo.tables.Userinfo;
import com.rulerbug.zoo.tables._Warning;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mypages extends SchemaImpl {

    private static final long serialVersionUID = -1843487377;

    /**
     * The reference instance of <code>mypages</code>
     */
    public static final Mypages MYPAGES = new Mypages();

    /**
     * The table <code>mypages.allBooks</code>.
     */
    public final Allbooks ALLBOOKS = com.rulerbug.zoo.tables.Allbooks.ALLBOOKS;

    /**
     * 权限信息
     */
    public final Limit LIMIT = com.rulerbug.zoo.tables.Limit.LIMIT;

    /**
     * The table <code>mypages.pages</code>.
     */
    public final Pages PAGES = com.rulerbug.zoo.tables.Pages.PAGES;

    /**
     * 角色信息
     */
    public final Role ROLE = com.rulerbug.zoo.tables.Role.ROLE;

    /**
     * The table <code>mypages.user</code>.
     */
    public final User USER = com.rulerbug.zoo.tables.User.USER;

    /**
     * VIEW
     */
    public final Userinfo USERINFO = com.rulerbug.zoo.tables.Userinfo.USERINFO;

    /**
     * The table <code>mypages._WARNING</code>.
     */
    public final _Warning _WARNING = com.rulerbug.zoo.tables._Warning._WARNING;

    /**
     * No further instances allowed
     */
    private Mypages() {
        super("mypages", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Allbooks.ALLBOOKS,
            Limit.LIMIT,
            Pages.PAGES,
            Role.ROLE,
            User.USER,
            Userinfo.USERINFO,
            _Warning._WARNING);
    }
}
