/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo;


import com.rulerbug.zoo.tables.Allbooks;
import com.rulerbug.zoo.tables.Pages;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mypages
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mypages.allBooks</code>.
     */
    public static final Allbooks ALLBOOKS = Allbooks.ALLBOOKS;

    /**
     * The table <code>mypages.pages</code>.
     */
    public static final Pages PAGES = Pages.PAGES;
}
