/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo;


import com.rulerbug.zoo.tables.Allbooks;
import com.rulerbug.zoo.tables.Limit;
import com.rulerbug.zoo.tables.Pages;
import com.rulerbug.zoo.tables.Postdata;
import com.rulerbug.zoo.tables.Role;
import com.rulerbug.zoo.tables.User;
import com.rulerbug.zoo.tables.Userinfo;
import com.rulerbug.zoo.tables._Warning;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mypages
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mypages.allBooks</code>.
     */
    public static final Allbooks ALLBOOKS = Allbooks.ALLBOOKS;

    /**
     * 权限信息
     */
    public static final Limit LIMIT = Limit.LIMIT;

    /**
     * The table <code>mypages.pages</code>.
     */
    public static final Pages PAGES = Pages.PAGES;

    /**
     * The table <code>mypages.postData</code>.
     */
    public static final Postdata POSTDATA = Postdata.POSTDATA;

    /**
     * 角色信息
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>mypages.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * VIEW
     */
    public static final Userinfo USERINFO = Userinfo.USERINFO;

    /**
     * The table <code>mypages._WARNING</code>.
     */
    public static final _Warning _WARNING = _Warning._WARNING;
}
