/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo.tables;


import com.rulerbug.zoo.Indexes;
import com.rulerbug.zoo.Keys;
import com.rulerbug.zoo.Mypages;
import com.rulerbug.zoo.tables.records.BooksRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Books extends TableImpl<BooksRecord> {

    private static final long serialVersionUID = 2056351832;

    /**
     * The reference instance of <code>mypages.books</code>
     */
    public static final Books BOOKS = new Books();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BooksRecord> getRecordType() {
        return BooksRecord.class;
    }

    /**
     * The column <code>mypages.books.id</code>. 书ID
     */
    public final TableField<BooksRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "书ID");

    /**
     * The column <code>mypages.books.bookName</code>. 书名
     */
    public final TableField<BooksRecord, String> BOOKNAME = createField(DSL.name("bookName"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "书名");

    /**
     * The column <code>mypages.books.author</code>. 作者
     */
    public final TableField<BooksRecord, String> AUTHOR = createField(DSL.name("author"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "作者");

    /**
     * The column <code>mypages.books.createTime</code>. 开始创作时间
     */
    public final TableField<BooksRecord, LocalDateTime> CREATETIME = createField(DSL.name("createTime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "开始创作时间");

    /**
     * The column <code>mypages.books.changeTime</code>. 最后一次修改时间
     */
    public final TableField<BooksRecord, LocalDateTime> CHANGETIME = createField(DSL.name("changeTime"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "最后一次修改时间");

    /**
     * Create a <code>mypages.books</code> table reference
     */
    public Books() {
        this(DSL.name("books"), null);
    }

    /**
     * Create an aliased <code>mypages.books</code> table reference
     */
    public Books(String alias) {
        this(DSL.name(alias), BOOKS);
    }

    /**
     * Create an aliased <code>mypages.books</code> table reference
     */
    public Books(Name alias) {
        this(alias, BOOKS);
    }

    private Books(Name alias, Table<BooksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Books(Name alias, Table<BooksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Books(Table<O> child, ForeignKey<O, BooksRecord> key) {
        super(child, key, BOOKS);
    }

    @Override
    public Schema getSchema() {
        return Mypages.MYPAGES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOKS_PRIMARY);
    }

    @Override
    public Identity<BooksRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOOKS;
    }

    @Override
    public UniqueKey<BooksRecord> getPrimaryKey() {
        return Keys.KEY_BOOKS_PRIMARY;
    }

    @Override
    public List<UniqueKey<BooksRecord>> getKeys() {
        return Arrays.<UniqueKey<BooksRecord>>asList(Keys.KEY_BOOKS_PRIMARY);
    }

    @Override
    public Books as(String alias) {
        return new Books(DSL.name(alias), this);
    }

    @Override
    public Books as(Name alias) {
        return new Books(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Books rename(String name) {
        return new Books(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Books rename(Name name) {
        return new Books(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
