/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo.tables.pojos;


import com.rulerbug.zoo.tables.interfaces.IAllbooks;

import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allbooks implements IAllbooks {

    private static final long serialVersionUID = -1754133089;

    private Long          id;
    private String        bookname;
    private String        author;
    private LocalDateTime createtime;
    private LocalDateTime changetime;

    public Allbooks() {}

    public Allbooks(IAllbooks value) {
        this.id = value.getId();
        this.bookname = value.getBookname();
        this.author = value.getAuthor();
        this.createtime = value.getCreatetime();
        this.changetime = value.getChangetime();
    }

    public Allbooks(
        Long          id,
        String        bookname,
        String        author,
        LocalDateTime createtime,
        LocalDateTime changetime
    ) {
        this.id = id;
        this.bookname = bookname;
        this.author = author;
        this.createtime = createtime;
        this.changetime = changetime;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String getBookname() {
        return this.bookname;
    }

    @Override
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    @Override
    public String getAuthor() {
        return this.author;
    }

    @Override
    public void setAuthor(String author) {
        this.author = author;
    }

    @Override
    public LocalDateTime getCreatetime() {
        return this.createtime;
    }

    @Override
    public void setCreatetime(LocalDateTime createtime) {
        this.createtime = createtime;
    }

    @Override
    public LocalDateTime getChangetime() {
        return this.changetime;
    }

    @Override
    public void setChangetime(LocalDateTime changetime) {
        this.changetime = changetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Allbooks (");

        sb.append(id);
        sb.append(", ").append(bookname);
        sb.append(", ").append(author);
        sb.append(", ").append(createtime);
        sb.append(", ").append(changetime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAllbooks from) {
        setId(from.getId());
        setBookname(from.getBookname());
        setAuthor(from.getAuthor());
        setCreatetime(from.getCreatetime());
        setChangetime(from.getChangetime());
    }

    @Override
    public <E extends IAllbooks> E into(E into) {
        into.from(this);
        return into;
    }
}
