/*
 * This file is generated by jOOQ.
 */
package com.rulerbug.zoo.tables.pojos;


import com.rulerbug.zoo.tables.interfaces.IPages;

import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pages implements IPages {

    private static final long serialVersionUID = 208524555;

    private Long          id;
    private Long          bookid;
    private Long          index;
    private String        title;
    private String        smalltitle;
    private String        context;
    private LocalDateTime firstcreattime;
    private LocalDateTime changetime;

    public Pages() {}

    public Pages(IPages value) {
        this.id = value.getId();
        this.bookid = value.getBookid();
        this.index = value.getIndex();
        this.title = value.getTitle();
        this.smalltitle = value.getSmalltitle();
        this.context = value.getContext();
        this.firstcreattime = value.getFirstcreattime();
        this.changetime = value.getChangetime();
    }

    public Pages(
        Long          id,
        Long          bookid,
        Long          index,
        String        title,
        String        smalltitle,
        String        context,
        LocalDateTime firstcreattime,
        LocalDateTime changetime
    ) {
        this.id = id;
        this.bookid = bookid;
        this.index = index;
        this.title = title;
        this.smalltitle = smalltitle;
        this.context = context;
        this.firstcreattime = firstcreattime;
        this.changetime = changetime;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public Long getBookid() {
        return this.bookid;
    }

    @Override
    public void setBookid(Long bookid) {
        this.bookid = bookid;
    }

    @Override
    public Long getIndex() {
        return this.index;
    }

    @Override
    public void setIndex(Long index) {
        this.index = index;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getSmalltitle() {
        return this.smalltitle;
    }

    @Override
    public void setSmalltitle(String smalltitle) {
        this.smalltitle = smalltitle;
    }

    @Override
    public String getContext() {
        return this.context;
    }

    @Override
    public void setContext(String context) {
        this.context = context;
    }

    @Override
    public LocalDateTime getFirstcreattime() {
        return this.firstcreattime;
    }

    @Override
    public void setFirstcreattime(LocalDateTime firstcreattime) {
        this.firstcreattime = firstcreattime;
    }

    @Override
    public LocalDateTime getChangetime() {
        return this.changetime;
    }

    @Override
    public void setChangetime(LocalDateTime changetime) {
        this.changetime = changetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pages (");

        sb.append(id);
        sb.append(", ").append(bookid);
        sb.append(", ").append(index);
        sb.append(", ").append(title);
        sb.append(", ").append(smalltitle);
        sb.append(", ").append(context);
        sb.append(", ").append(firstcreattime);
        sb.append(", ").append(changetime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPages from) {
        setId(from.getId());
        setBookid(from.getBookid());
        setIndex(from.getIndex());
        setTitle(from.getTitle());
        setSmalltitle(from.getSmalltitle());
        setContext(from.getContext());
        setFirstcreattime(from.getFirstcreattime());
        setChangetime(from.getChangetime());
    }

    @Override
    public <E extends IPages> E into(E into) {
        into.from(this);
        return into;
    }
}
